<?php
add_action( 'init', 'mib_register_taxomomies', 10 );

function get_icon_base64 ( $name ) {
    return file_get_contents( get_template_directory_uri() . "/assets/images/icons_base64/$name.txt" );
};
function create_custom_post_types_and_taxonomies() {
    $programs_labels = array(
        'name'                  => 'Програми навчання',
        'singular_name'         => 'Програма навчання',
        'menu_name'             => 'Програми навчання',
        'name_admin_bar'        => 'Програма навчання',
        'archives'              => 'Архіви програм',
        'attributes'            => 'Атрибути програми',
        'parent_item_colon'     => 'Батьківська програма:',
        'all_items'             => 'Всі програми',
        'add_new_item'          => 'Додати нову програму',
        'add_new'               => 'Додати нову',
        'new_item'              => 'Нова програма',
        'edit_item'             => 'Редагувати програму',
        'update_item'           => 'Оновити програму',
        'view_item'             => 'Переглянути програму',
        'view_items'            => 'Переглянути програми',
        'search_items'          => 'Пошук програм',
        'not_found'             => 'Не знайдено',
        'not_found_in_trash'    => 'Не знайдено в кошику',
        'featured_image'        => 'Головне зображення',
        'set_featured_image'    => 'Встановити головне зображення',
        'remove_featured_image' => 'Видалити головне зображення',
        'use_featured_image'    => 'Використати як головне зображення',
        'insert_into_item'      => 'Вставити в програму',
        'uploaded_to_this_item' => 'Завантажено до цієї програми',
        'items_list'            => 'Список програм',
        'items_list_navigation' => 'Навігація по списку програм',
        'filter_items_list'     => 'Фільтрувати список програм',
    );
    
    $programs_args = array(
        'label'               => 'Програма навчання',
        'description'         => 'Програми навчання',
        'labels'              => $programs_labels,
        'supports'            => array('title', 'editor', 'thumbnail', 'excerpt'),
        'taxonomies'          => array('program_category', 'post_tag'),
        'hierarchical'        => false,
        'public'              => true,
        'show_ui'             => true,
        'show_in_menu'        => true,
        'menu_position'       => 21,
        'menu_icon'           => 'dashicons-welcome-learn-more',
        'show_in_admin_bar'   => true,
        'show_in_nav_menus'   => true,
        'can_export'          => true,
        'has_archive'         => false,
        'exclude_from_search' => false,
        'publicly_queryable'  => true,
        'capability_type'     => 'page',
        'show_in_rest'        => true,
    );
    
    $events_labels = array(
        'name'                  => __( 'Події' ),
        'singular_name'         => __( 'Подія' ),
        'menu_name'             => __( 'Події' ),
        'name_admin_bar'        => __( 'Подія' ),
        'archives'              => __( 'Архіви подій' ),
        'attributes'            => __( 'Атрибути подій' ),
        'parent_item_colon'     => __( 'Батьківська подія:' ),
        'all_items'             => __( 'Всі події' ),
        'add_new_item'          => __( 'Додати нову подію' ),
        'add_new'               => __( 'Додати нову' ),
        'new_item'              => __( 'Нова подія' ),
        'edit_item'             => __( 'Редагувати подію' ),
        'update_item'           => __( 'Оновити подію' ),
        'view_item'             => __( 'Переглянути подію' ),
        'view_items'            => __( 'Переглянути події' ),
        'search_items'          => __( 'Пошук подій' ),
        'not_found'             => __( 'Не знайдено' ),
        'not_found_in_trash'    => __( 'Не знайдено в кошику' ),
        'featured_image'        => __( 'Головне зображення' ),
        'set_featured_image'    => __( 'Встановити головне зображення' ),
        'remove_featured_image' => __( 'Видалити головне зображення' ),
        'use_featured_image'    => __( 'Використати як головне зображення' ),
        'insert_into_item'      => __( 'Вставити в подію' ),
        'uploaded_to_this_item' => __( 'Завантажено до цієї події' ),
        'items_list'            => __( 'Список подій' ),
        'items_list_navigation' => __( 'Навігація по списку подій' ),
        'filter_items_list'     => __( 'Фільтрувати список подій' ),
    );
    
    $events_args = array(
        'label'               => __( 'Події' ),
        'description'         => '',
        'labels'              => $events_labels,
        'supports'            => array('title', 'thumbnail', 'excerpt'),
        'taxonomies'          => array('event_category', 'post_tag'),
        'hierarchical'        => false,
        'public'              => true,
        'show_ui'             => true,
        'show_in_menu'        => true,
        'menu_position'       => 21,
        'menu_icon'           => 'dashicons-calendar',
        'show_in_admin_bar'   => true,
        'show_in_nav_menus'   => true,
        'can_export'          => true,
        'has_archive'         => false,
        'exclude_from_search' => false,
        'publicly_queryable'  => true,
        'capability_type'     => 'page',
        'show_in_rest'        => true,
    );

    $accreditations_labels = array(
        'name'                  => __( 'Акредитації' ),
        'singular_name'         => __( 'Акредитація' ),
        'menu_name'             => __( 'Акредитації' ),
        'name_admin_bar'        => __( 'Акредитація' ),
        'archives'              => __( 'Архіви акредитацій' ),
        'attributes'            => __( 'Атрибути акредитацій' ),
        'parent_item_colon'     => __( 'Батьківська акредитація:' ),
        'all_items'             => __( 'Всі акредитації' ),
        'add_new_item'          => __( 'Додати нову акредитацію' ),
        'add_new'               => __( 'Додати нову' ),
        'new_item'              => __( 'Нова акредитація' ),
        'edit_item'             => __( 'Редагувати акредитацію' ),
        'update_item'           => __( 'Оновити акредитацію' ),
        'view_item'             => __( 'Переглянути акредитацію' ),
        'view_items'            => __( 'Переглянути акредитації' ),
        'search_items'          => __( 'Пошук акредитацій' ),
        'not_found'             => __( 'Не знайдено' ),
        'not_found_in_trash'    => __( 'Не знайдено в кошику' ),
        'featured_image'        => __( 'Головне зображення' ),
        'set_featured_image'    => __( 'Встановити головне зображення' ),
        'remove_featured_image' => __( 'Видалити головне зображення' ),
        'use_featured_image'    => __( 'Використати як головне зображення' ),
        'insert_into_item'      => __( 'Вставити в акредитацію' ),
        'uploaded_to_this_item' => __( 'Завантажено до цієї акредитації' ),
        'items_list'            => __( 'Список акредитацій' ),
        'items_list_navigation' => __( 'Навігація по списку акредитацій' ),
        'filter_items_list'     => __( 'Фільтрувати список акредитацій' ),
    );
    
    $accreditations_args = array(
        'label'               => __( 'Акредитації' ),
        'description'         => '',
        'labels'              => $accreditations_labels,
        'supports'            => array('title', 'editor', 'thumbnail', 'excerpt'),
        'taxonomies'          => array('accreditation_category', 'post_tag'),
        'hierarchical'        => false,
        'public'              => true,
        'show_ui'             => true,
        'show_in_menu'        => true,
        'menu_position'       => 21,
        'menu_icon'           => 'dashicons-media-document',
        'show_in_admin_bar'   => true,
        'show_in_nav_menus'   => true,
        'can_export'          => true,
        'has_archive'         => false,
        'exclude_from_search' => true,
        'publicly_queryable'  => true,
        'capability_type'     => 'page',
        'show_in_rest'        => true,
    );
    
    register_post_type('programs', $programs_args);
    register_post_type('events', $events_args);
    register_post_type('accreditations', $accreditations_args);

    register_post_type( 'teachers', [
        'label' => null,
        'labels' => [
            'name'                  => __( 'Викладачі' ),
            'singular_name'         => __( 'Викладач' ),
            'add_new'               => __( 'Додати нового викладача' ),
            'add_new_item'          => __( 'Додати викладача' ),
            'edit_item'             => __( 'Редагувати викладача' ),
            'new_item'              => __( 'Новий викладач' ),
            'view_item'             => __( 'Переглянути викладача' ),
            'search_items'          => __( 'Пошук викладачів' ),
            'not_found'             => __( 'Не знайдено викладачів' ),
            'not_found_in_trash'    => __( 'Не знайдено викладачів в корзині' ),
            'menu_name'             => __( 'Викладачі' ),
        ],
        'description'         => '',
        'public'              => true,
        'publicly_queryable'  => true,
        'show_in_menu'        => true,
        'show_in_rest'        => true,
        'rest_base'           => null,
        'show_in_nav_menus'   => true,
        'menu_icon'           => get_icon_base64( "teachers" ),
        'hierarchical'        => false,
        'supports'            => ['title', 'thumbnail', 'excerpt', 'editor'],
        'taxonomies'          => ['program_category', 'teacher_category', 'companies'],
        'has_archive'         => false,
        'rewrite'             => true,
        'query_var'           => true,
    ] );

    register_post_type( 'students', [
        'label' => null,
        'labels' => [
            'name'                  => __( 'Випускники' ),
            'singular_name'         => __( 'Випускник' ),
            'add_new'               => __( 'Додати нового випускника' ),
            'add_new_item'          => __( 'Додати випускника' ),
            'edit_item'             => __( 'Редагувати випускника' ),
            'new_item'              => __( 'Новий випускник' ),
            'view_item'             => __( 'Переглянути випускника' ),
            'search_items'          => __( 'Пошук випускників' ),
            'not_found'             => __( 'Не знайдено випускників' ),
            'not_found_in_trash'    => __( 'Не знайдено випускників в корзині' ),
            'menu_name'             => __( 'Випускники' ),
        ],
        'description'         => '',
        'public'              => true,
        'publicly_queryable'  => true,
        'show_in_menu'        => true,
        'show_in_rest'        => true,
        'rest_base'           => null,
        'show_in_nav_menus'   => true,
        'menu_icon'           => get_icon_base64( "student" ),
        'hierarchical'        => false,
        'supports'            => ['title', 'thumbnail', 'excerpt', 'editor' ],
        'taxonomies'          => ['program_category', 'student_category', 'companies'],
        'has_archive'         => false,
        'rewrite'             => true,
        'query_var'           => true,
    ] );

    register_post_type( 'members', [
        'label' => null,
        'labels' => [
            'name'                  => __( 'Учасники' ),
            'singular_name'         => __( 'Учасник' ),
            'menu_name'             => __( 'Учасники' ),
            'name_admin_bar'        => __( 'Учасник' ),
            'archives'              => __( 'Архів учасників' ),
            'attributes'            => __( 'Атрибути учасника' ),
            'parent_item_colon'     => __( 'Батьківський учасник:' ),
            'all_items'             => __( 'Всі учасники' ),
            'add_new_item'          => __( 'Додати нового учасника' ),
            'add_new'               => __( 'Додати новий' ),
            'new_item'              => __( 'Новий учасник' ),
            'edit_item'             => __( 'Редагувати учасника' ),
            'update_item'           => __( 'Оновити учасника' ),
            'view_item'             => __( 'Переглянути учасника' ),
            'view_items'            => __( 'Переглянути учасників' ),
            'search_items'          => __( 'Пошук учасника' ),
            'not_found'             => __( 'Не знайдено' ),
            'not_found_in_trash'    => __( 'Не знайдено в кошику' ),
            'featured_image'        => __( 'Зображення' ),
            'set_featured_image'    => __( 'Встановити зображення' ),
            'remove_featured_image' => __( 'Видалити зображення' ),
            'use_featured_image'    => __( 'Використати як зображення' ),
            'insert_into_item'      => __( 'Вставити в учасника' ),
            'uploaded_to_this_item' => __( 'Завантажено для цього учасника' ),
            'items_list'            => __( 'Список учасників' ),
            'items_list_navigation' => __( 'Навігація по учасниках' ),
            'filter_items_list'     => __( 'Фільтрувати список учасників' ),
        ],
        'description'         => '',
        'public'              => true,
        'publicly_queryable'  => true,
        'show_in_menu'        => true,
        'show_in_rest'        => true,
        'rest_base'           => null,
        'show_in_nav_menus'   => true,
        'menu_icon'           => 'dashicons-groups',
        'menu_position'       => 30,
        'hierarchical'        => false,
        'supports'            => ['title', 'thumbnail', 'excerpt', 'editor' ],
        'has_archive'         => false,
        'rewrite'             => true,
        'query_var'           => true,
    ] );
}

function mib_register_taxomomies() {
    
    register_taxonomy( 'program_category', ['programs', 'students', 'teachers'], [
        'labels' => [
            'name'              => 'Категорії програм',
            'singular_name'     => 'Категорія програми',
            'search_items'      => 'Пошук категорій програм',
            'all_items'         => 'Всі категорії програм',
            'parent_item'       => 'Батьківська категорія програми',
            'parent_item_colon' => 'Батьківська категорія програми:',
            'edit_item'         => 'Редагувати категорію програми',
            'update_item'       => 'Оновити категорію програми',
            'add_new_item'      => 'Додати нову категорію програми',
            'new_item_name'     => 'Назва нової категорії програми',
            'menu_name'         => 'Категорії програм',
        ],
        'public'              => true,
        'hierarchical'        => true,
        'show_in_rest'        => true,
        'show_admin_column'   => true,
        'rewrite'             => array(
            'slug'                => 'program-category',
            'with_front'          => false,
            'hierarchical'        => true
        ),
    ]);

    register_taxonomy( 'event_category', ['events'], [
        'labels' => [
            'name'              => 'Категорії подій',
            'singular_name'     => 'Категорія події',
            'search_items'      => 'Пошук категорій подій',
            'all_items'         => 'Всі категорії подій',
            'parent_item'       => 'Батьківська категорія події',
            'parent_item_colon' => 'Батьківська категорія події:',
            'edit_item'         => 'Редагувати категорію події',
            'update_item'       => 'Оновити категорію події',
            'add_new_item'      => 'Додати нову категорію події',
            'new_item_name'     => 'Назва нової категорії події',
            'menu_name'         => 'Категорії подій',
        ],
        'public'              => true,
        'hierarchical'        => true,
        'show_in_rest'        => true,
        'show_admin_column'   => true,
        'rewrite'             => array('slug' => 'event-category'),
    ]);

    register_taxonomy( 'accreditation_category', ['accreditations'], [
        'labels' => [
            'name'              => 'Категорії акредитацій',
            'singular_name'     => 'Категорія акредитації',
            'search_items'      => 'Пошук категорій акредитацій',
            'all_items'         => 'Всі категорії акредитацій',
            'parent_item'       => 'Батьківська категорія акредитації',
            'parent_item_colon' => 'Батьківська категорія акредитації:',
            'edit_item'         => 'Редагувати категорію акредитації',
            'update_item'       => 'Оновити категорію акредитації',
            'add_new_item'      => 'Додати нову категорію акредитації',
            'new_item_name'     => 'Назва нової категорії акредитації',
            'menu_name'         => 'Категорії акредитацій',
        ],
        'public'              => true,
        'hierarchical'        => true,
        'show_in_rest'        => true,
        'show_admin_column'   => true,
        'rewrite'             => array('slug' => 'accreditation-category'),
    ]);

    register_taxonomy( 'teacher_category', ['programs', 'teachers'], [
        'labels' => [
            'name'              => 'Категорії викладачів',
            'singular_name'     => 'Категорія викладача',
            'search_items'      => 'Пошук категорій викладачів',
            'all_items'         => 'Всі категорії викладачів',
            'parent_item'       => 'Батьківська категорія викладача',
            'parent_item_colon' => 'Батьківська категорія викладача:',
            'edit_item'         => 'Редагувати категорію викладача',
            'update_item'       => 'Оновити категорію викладача',
            'add_new_item'      => 'Додати нову категорію викладача',
            'new_item_name'     => 'Назва нової категорії викладача',
            'menu_name'         => 'Категорії викладачів',
        ],
        'public'              => true,
        'hierarchical'        => true, 
        'show_in_rest'        => true,
        'show_admin_column'   => true,
        'rewrite'             => array('slug' => 'teacher-category'),
    ]);

    register_taxonomy( 'student_category', ['students'], [
        'labels' => [
            'name'              => 'Категорії випускників',
            'singular_name'     => 'Категорія випускника',
            'search_items'      => 'Пошук категорій випускників',
            'all_items'         => 'Всі категорії випускників',
            'parent_item'       => 'Батьківська категорія випускника',
            'parent_item_colon' => 'Батьківська категорія випускника:',
            'edit_item'         => 'Редагувати категорію випускника',
            'update_item'       => 'Оновити категорію випускника',
            'add_new_item'      => 'Додати нову категорію випускника',
            'new_item_name'     => 'Назва нової категорії випускника',
            'menu_name'         => 'Категорії випускників',
        ],
        'public'              => true,
        'hierarchical'        => true,
        'show_in_rest'        => true,
        'show_admin_column'   => true,
        'rewrite'             => array('slug' => 'student-category'),
    ]);

    register_taxonomy( 'companies', ['teachers', 'students'], [
        'labels' => [
            'name'              => 'Компанії',
            'singular_name'     => 'Компанія',
            'search_items'      => 'Пошук компаній',
            'all_items'         => 'Всі компанії',
            'parent_item'       => 'Батьківська компанія',
            'parent_item_colon' => 'Батьківська компанія:',
            'edit_item'         => 'Редагувати компанію',
            'update_item'       => 'Оновити компанію',
            'add_new_item'      => 'Додати нову компанію',
            'new_item_name'     => 'Назва нової компанії',
            'menu_name'         => 'Компанії',
        ],
        'public'              => true,
        'hierarchical'        => true,
        'show_in_rest'        => true,
        'show_admin_column'   => true,
    ]);
}

add_action('init', 'create_custom_post_types_and_taxonomies', 0);