<?php
add_action( 'init', 'mib_register_taxomomies', 10 );

function get_icon_base64 ( $name ) {
    return file_get_contents( get_template_directory_uri() . "/assets/images/icons_base64/$name.txt" );
};
function create_custom_post_types_and_taxonomies() {
    $programs_labels = array(
        'name'                  => 'Програми навчання',
        'singular_name'         => 'Програма навчання',
        'menu_name'             => 'Програми навчання',
        'name_admin_bar'        => 'Програма навчання',
        'archives'              => 'Архіви програм',
        'attributes'            => 'Атрибути програми',
        'parent_item_colon'     => 'Батьківська програма:',
        'all_items'             => 'Всі програми',
        'add_new_item'          => 'Додати нову програму',
        'add_new'               => 'Додати нову',
        'new_item'              => 'Нова програма',
        'edit_item'             => 'Редагувати програму',
        'update_item'           => 'Оновити програму',
        'view_item'             => 'Переглянути програму',
        'view_items'            => 'Переглянути програми',
        'search_items'          => 'Пошук програм',
        'not_found'             => 'Не знайдено',
        'not_found_in_trash'    => 'Не знайдено в кошику',
        'featured_image'        => 'Головне зображення',
        'set_featured_image'    => 'Встановити головне зображення',
        'remove_featured_image' => 'Видалити головне зображення',
        'use_featured_image'    => 'Використати як головне зображення',
        'insert_into_item'      => 'Вставити в програму',
        'uploaded_to_this_item' => 'Завантажено до цієї програми',
        'items_list'            => 'Список програм',
        'items_list_navigation' => 'Навігація по списку програм',
        'filter_items_list'     => 'Фільтрувати список програм',
    );
    
    $programs_args = array(
        'label'               => 'Програма навчання',
        'description'         => 'Програми навчання',
        'labels'              => $programs_labels,
        'supports'            => array('title', 'editor', 'thumbnail', 'excerpt'),
        'taxonomies'          => array('program_category', 'post_tag'),
        'hierarchical'        => false,
        'public'              => true,
        'show_ui'             => true,
        'show_in_menu'        => true,
        'menu_position'       => 21,
        'menu_icon'           => 'dashicons-welcome-learn-more',
        'show_in_admin_bar'   => true,
        'show_in_nav_menus'   => true,
        'can_export'          => true,
        'has_archive'         => true,
        'exclude_from_search' => false,
        'publicly_queryable'  => true,
        'capability_type'     => 'page',
        'show_in_rest'        => true,
    );
    
    $events_labels = array(
        'name'                  => __( 'Події' ),
        'singular_name'         => __( 'Подія' ),
        'menu_name'             => __( 'Події' ),
        'name_admin_bar'        => __( 'Подія' ),
        'archives'              => __( 'Архіви подій' ),
        'attributes'            => __( 'Атрибути подій' ),
        'parent_item_colon'     => __( 'Батьківська подія:' ),
        'all_items'             => __( 'Всі події' ),
        'add_new_item'          => __( 'Додати нову подію' ),
        'add_new'               => __( 'Додати нову' ),
        'new_item'              => __( 'Нова подія' ),
        'edit_item'             => __( 'Редагувати подію' ),
        'update_item'           => __( 'Оновити подію' ),
        'view_item'             => __( 'Переглянути подію' ),
        'view_items'            => __( 'Переглянути події' ),
        'search_items'          => __( 'Пошук подій' ),
        'not_found'             => __( 'Не знайдено' ),
        'not_found_in_trash'    => __( 'Не знайдено в кошику' ),
        'featured_image'        => __( 'Головне зображення' ),
        'set_featured_image'    => __( 'Встановити головне зображення' ),
        'remove_featured_image' => __( 'Видалити головне зображення' ),
        'use_featured_image'    => __( 'Використати як головне зображення' ),
        'insert_into_item'      => __( 'Вставити в подію' ),
        'uploaded_to_this_item' => __( 'Завантажено до цієї події' ),
        'items_list'            => __( 'Список подій' ),
        'items_list_navigation' => __( 'Навігація по списку подій' ),
        'filter_items_list'     => __( 'Фільтрувати список подій' ),
    );
    
    $events_args = array(
        'label'               => __( 'Події' ),
        'description'         => '',
        'labels'              => $events_labels,
        'supports'            => array('title', 'editor', 'thumbnail', 'excerpt'),
        'taxonomies'          => array('event_category', 'post_tag'),
        'hierarchical'        => false,
        'public'              => true,
        'show_ui'             => true,
        'show_in_menu'        => true,
        'menu_position'       => 21,
        'menu_icon'           => 'dashicons-calendar',
        'show_in_admin_bar'   => true,
        'show_in_nav_menus'   => true,
        'can_export'          => true,
        'has_archive'         => true,
        'exclude_from_search' => false,
        'publicly_queryable'  => true,
        'capability_type'     => 'page',
        'show_in_rest'        => true,
    );

    $accreditations_labels = array(
        'name'                  => __( 'Акредитації' ),
        'singular_name'         => __( 'Акредитація' ),
        'menu_name'             => __( 'Акредитації' ),
        'name_admin_bar'        => __( 'Акредитація' ),
        'archives'              => __( 'Архіви акредитацій' ),
        'attributes'            => __( 'Атрибути акредитацій' ),
        'parent_item_colon'     => __( 'Батьківська акредитація:' ),
        'all_items'             => __( 'Всі акредитації' ),
        'add_new_item'          => __( 'Додати нову акредитацію' ),
        'add_new'               => __( 'Додати нову' ),
        'new_item'              => __( 'Нова акредитація' ),
        'edit_item'             => __( 'Редагувати акредитацію' ),
        'update_item'           => __( 'Оновити акредитацію' ),
        'view_item'             => __( 'Переглянути акредитацію' ),
        'view_items'            => __( 'Переглянути акредитації' ),
        'search_items'          => __( 'Пошук акредитацій' ),
        'not_found'             => __( 'Не знайдено' ),
        'not_found_in_trash'    => __( 'Не знайдено в кошику' ),
        'featured_image'        => __( 'Головне зображення' ),
        'set_featured_image'    => __( 'Встановити головне зображення' ),
        'remove_featured_image' => __( 'Видалити головне зображення' ),
        'use_featured_image'    => __( 'Використати як головне зображення' ),
        'insert_into_item'      => __( 'Вставити в акредитацію' ),
        'uploaded_to_this_item' => __( 'Завантажено до цієї акредитації' ),
        'items_list'            => __( 'Список акредитацій' ),
        'items_list_navigation' => __( 'Навігація по списку акредитацій' ),
        'filter_items_list'     => __( 'Фільтрувати список акредитацій' ),
    );
    
    $accreditations_args = array(
        'label'               => __( 'Акредитації' ),
        'description'         => '',
        'labels'              => $accreditations_labels,
        'supports'            => array('title', 'editor', 'thumbnail', 'excerpt'),
        // 'taxonomies'          => array('accreditations_category', 'post_tag'),
        'hierarchical'        => false,
        'public'              => true,
        'show_ui'             => true,
        'show_in_menu'        => true,
        'menu_position'       => 21,
        'menu_icon'           => 'dashicons-media-document',
        'show_in_admin_bar'   => true,
        'show_in_nav_menus'   => true,
        'can_export'          => true,
        'has_archive'         => true,
        'exclude_from_search' => false,
        'publicly_queryable'  => true,
        'capability_type'     => 'page',
        'show_in_rest'        => true,
    );
    
    register_post_type('programs', $programs_args);
    register_post_type('events', $events_args);

    register_post_type( 'teachers', [
        'label' => null,
        'labels' => [
            'name'                  => __( 'Викладачі' ),
            'singular_name'         => __( 'Викладач' ),
            'add_new'               => __( 'Додати нового викладача' ),
            'add_new_item'          => __( 'Додати викладача' ),
            'edit_item'             => __( 'Редагувати викладача' ),
            'new_item'              => __( 'Новий викладач' ),
            'view_item'             => __( 'Переглянути викладача' ),
            'search_items'          => __( 'Пошук викладачів' ),
            'not_found'             => __( 'Не знайдено викладачів' ),
            'not_found_in_trash'    => __( 'Не знайдено викладачів в корзині' ),
            'menu_name'             => __( 'Викладачі' ),
        ],
        'description'         => '',
        'public'              => true,
        'publicly_queryable'  => true,
        'show_in_menu'        => true,
        'show_in_rest'        => true,
        'rest_base'           => null,
        'show_in_nav_menus'   => true,
        'menu_icon'           => get_icon_base64( "teachers" ),
        'hierarchical'        => false,
        'supports'            => ['title', 'thumbnail', 'excerpt', 'editor'], // 'title','editor','author','thumbnail','excerpt','trackbacks','custom-fields','comments','revisions','page-attributes','post-formats'
        'taxonomies'          => [],
        'has_archive'         => true,
        'rewrite'             => true,
        'query_var'           => true,
    ] );

    register_post_type( 'students', [
        'label' => null,
        'labels' => [
            'name'                  => __( 'Випускники' ),
            'singular_name'         => __( 'Випускник' ),
            'add_new'               => __( 'Додати нового випускника' ),
            'add_new_item'          => __( 'Додати випускника' ),
            'edit_item'             => __( 'Редагувати випускника' ),
            'new_item'              => __( 'Новий випускник' ),
            'view_item'             => __( 'Переглянути випускника' ),
            'search_items'          => __( 'Пошук випускників' ),
            'not_found'             => __( 'Не знайдено випускників' ),
            'not_found_in_trash'    => __( 'Не знайдено випускників в корзині' ),
            'menu_name'             => __( 'Випускники' ),
        ],
        'description'         => '',
        'public'              => true,
        'publicly_queryable'  => true,
        'show_in_menu'        => true,
        'show_in_rest'        => true,
        'rest_base'           => null,
        'show_in_nav_menus'   => true,
        'menu_icon'           => get_icon_base64( "student" ),
        'hierarchical'        => false,
        'supports'            => ['title', 'thumbnail', 'excerpt'], // 'title','editor','author','thumbnail','excerpt','trackbacks','custom-fields','comments','revisions','page-attributes','post-formats'
        'taxonomies'          => [],
        'has_archive'         => true,
        'rewrite'             => true,
        'query_var'           => true,
    ] );
}

function mib_register_taxomomies() {
    register_taxonomy( 'companies', ['teachers', 'students'], [
        'labels' => [
            'name'          => __( 'Companies' ),
            'singular_name' => __( 'Company' ),
            'add_new_item'  => __( 'Add new company' ),
            'new_item_name' => __( 'New company' ),
            'menu_name'     => __( 'Companies' ),
        ],
        'public'              => true,
        'hierarchical'        => true,
        'show_in_rest'        => true,
        'show_admin_column'   => true,
    ]);
}

add_action('init', 'create_custom_post_types_and_taxonomies', 0);